name: Matrix Deployment
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 20
            operating-system: macos-latest
        exclude:
          - node-version: 16
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-${{ matrix.node-version }}